### ISSUE TITLE
Button action upon pressing enter

### ISSUE THREAD

**Issue by c0derMo** [loernwerk/loernwerk#47]
Not sure how feasable this is, but I think it's be a good option to allow buttons to be activated by pressing enter, e.g. indicated by a new prop in ButtonComponent

**Comment by Kr0nox** [comment]
Where do we want that that? For example in the AccountDetailsEditContainer we have multiple buttons. Do we want this here and Enter presses the save button?

**Comment by c0derMo** [comment]
Would be an option, I think in multi-button-views pressing enter to confirm isn't too important, we declare one button to serve as the "Confirm"/Enter-Button, but I'd argue this is mainly for views where we only have a single button, e.g. login, sequence creation, etc.

**Comment by c0derMo** [comment]
Also, while we're reworking buttons, we could also add a bit of color to the buttons, to not make everything just gray (suggestion by @a-bumblebee)

**Comment by c0derMo** [comment]
Update: I've done a bit of research, I'm not sure if there's an easy way to trigger a button action upon pressing enter, but we could move that functionality to the TextInputComponent, so we could e.g. confirm upon pressing enter in the Password field in login, name field in CreateNewSequence, etc.

Button color is still something I'd add at some point

**Comment by Kr0nox** [comment]
I think the correct way would be doing it with forms like this: `<form v-on:submit.prevent="submit()">`

**Comment by c0derMo** [comment]
>

**Comment by c0derMo** [comment]
> I think the correct way would be doing it with forms like this: `<form v-on:submit.prevent="submit()">`

This didn't work for me, I think you have to be focussed on an input inside the form in order for this to work properly, which isn't something the ButtonComponent can achieve I think.

(Accidentially closed this prior, reopening it)
