### ISSUE TITLE
SequenceEditView - LanguageSelector and LightDarkSwitch displayed in EmbedContent

### ISSUE THREAD

**Issue by a-bumblebee** [loernwerk/loernwerk#52]
When inputting an invalid url for embed content, in Firefox the LanguageSelector and the LightDarkSwitch are displayed on the slide.

**Comment by c0derMo** [comment]
Quickest fix I can think of would be checking if the url to embed is valid (via the default `URL` constructor) and only actually embed it if the URL is valid

**Comment by Kr0nox** [comment]
I think the problem is that it interprets this as a relativ URL and therefore wants to display something from our website. therefor it loads the stuff from the Main.vue file and the router cant find a valid page then
